### ISSUE TITLE
Increment version code

### ISSUE THREAD

**Issue by lu-x** [engSERGIU/React#6]
@engSERGIU 
I think you'll have to increment the version code in your https://github.com/engSERGIU/React/blob/master/app/build.gradle to make the release accessible on f-droid :wink:

**Comment by ghost** [comment]
The app is not update-able because upstream decided to switch the package id. Apart from that, a new release would require a higher versioncode, indeed.

**Comment by ghost** [comment]
Also note: 

1.3.0 was tagged (with a changed tagging scheme), but build.gradle still says `versionName '1.2.1'`.

**Comment by engSERGIU** [comment]
@kas70 
@krt16s 
fixed

**Comment by lu-x** [comment]
version code is still 1.

**Comment by engSERGIU** [comment]
@kas70 
??
What shall I change?

**Comment by engSERGIU** [comment]
What shall I change now?

@kas70 
@krt16s

**Comment by ghost** [comment]
Since the package id changed, upgrading the versioncode is not necessary. Any following version needs to have a higher integer value as versioncode. E.g. in build.gradle set `versionCode 1` to `versionCode 2`. See https://developer.android.com/studio/publish/versioning.html for an explanation on versionName and versionCode.

**Comment by lu-x** [comment]
> Since the package id changed, upgrading the versioncode is not necessary.

Yes of course, sorry. Didn't take this into account.
